# ---------- СТАДИЯ 1: СБОРКА REACT -----------
FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

# ---------- СТАДИЯ 2: NGINX -----------
FROM nginx:1.27-alpine

# Удаляем дефолтную конфигурацию
RUN rm -rf /usr/share/nginx/html/*

# Копируем билд фронта
COPY --from=build /app/dist /usr/share/nginx/html

# Добавляем кастомный конфиг Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]